
[env]
TERM = "xterm-256color"

[window]
# dimensions.columns = 135
# dimensions.lines = 37 

padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.87
blur = true

# option_as_alt = "Both"

# startup_mode = "Fullscreen"

[font]
size = 15

[font.normal]
# family="Hack Nerd Font Mono"
family="SauceCodePro Nerd Font"

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    # "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]
# family="Source Code Pro"
# family="Monaco"
# family="JetBrainsMono Nerd Font"
